# Generated by Django 4.2.1 on 2023-08-24 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(help_text='Máximo 200 caracteres', max_length=200, verbose_name='titulo')),
                ('description', models.CharField(help_text='Máximo 300 caracteres', max_length=300, verbose_name='descricao')),
                ('creation', models.DateTimeField(auto_now=True, verbose_name='creation')),
                ('start', models.DateTimeField(verbose_name='inicio')),
                ('end', models.DateTimeField(verbose_name='fim')),
                ('last_change', models.DateTimeField(auto_now=True, verbose_name='ultima_alteracao')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
